# Generated by Django 5.2.17 on 2026-09-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.uploads


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_seed_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.TextField()),
            ],
            options={
                "db_table": "customer_connections",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="avatar",
            field=models.ImageField(blank=True, upload_to=apps.accounts.uploads.avatar_path),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Женский"), ("male", "Мужской"), ("other", "Другой")],
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="customerprofile",
            constraint=models.CheckConstraint(
                condition=models.Q(("gender__in", ["", "female", "male", "other"])),
                name="customer_profile_valid_gender",
            ),
        ),
        migrations.AddField(
            model_name="customerconnection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="customerconnection",
            constraint=models.CheckConstraint(
                condition=models.Q(("label", ""), _negated=True),
                name="customer_connection_label_not_empty",
            ),
        ),
    ]
