# Generated by Django 5.2.17 on 2026-09-12 08:36

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.accounts.uploads


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customerconnection_customerprofile_avatar_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customeraddress",
            options={
                "verbose_name": "Адрес покупателя",
                "verbose_name_plural": "Адреса покупателей",
            },
        ),
        migrations.AlterModelOptions(
            name="customerconnection",
            options={
                "ordering": ["-created_at", "-pk"],
                "verbose_name": "Запись окружения",
                "verbose_name_plural": "Окружение покупателей",
            },
        ),
        migrations.AlterModelOptions(
            name="customerprofile",
            options={
                "verbose_name": "Профиль покупателя",
                "verbose_name_plural": "Профили покупателей",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Роль", "verbose_name_plural": "Роли"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Пользователь", "verbose_name_plural": "Пользователи"},
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={"verbose_name": "Назначение роли", "verbose_name_plural": "Назначения ролей"},
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="apartment",
            field=models.CharField(blank=True, max_length=30, verbose_name="Квартира"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="building",
            field=models.CharField(blank=True, max_length=30, verbose_name="Корпус/строение"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Город"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="delivery_comment",
            field=models.TextField(blank=True, verbose_name="Комментарий для доставки"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="entrance",
            field=models.CharField(blank=True, max_length=30, verbose_name="Подъезд"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="floor",
            field=models.CharField(blank=True, max_length=10, verbose_name="Этаж"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="house",
            field=models.CharField(max_length=30, verbose_name="Дом"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="intercom",
            field=models.CharField(blank=True, max_length=30, verbose_name="Домофон"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="Адрес по умолчанию"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="Широта",
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="Долгота",
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Почтовый индекс"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="recipient_name",
            field=models.CharField(max_length=200, verbose_name="Имя получателя"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="recipient_phone",
            field=models.CharField(
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9]{7,15}$", "Введите телефон: 7–15 цифр, возможен +."
                    )
                ],
                verbose_name="Телефон получателя",
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="street",
            field=models.CharField(max_length=200, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Название адреса"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="customerconnection",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="customerconnection",
            name="label",
            field=models.TextField(verbose_name="Запись"),
        ),
        migrations.AlterField(
            model_name="customerconnection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="customerconnection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="environment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, upload_to=apps.accounts.uploads.avatar_path, verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Женский"), ("male", "Мужской"), ("other", "Другой")],
                max_length=10,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="marketing_consent",
            field=models.BooleanField(default=False, verbose_name="Согласие на рассылку"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Заметки"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="customerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.SlugField(
                choices=[
                    ("customer", "Покупатель"),
                    ("operator", "Оператор"),
                    ("admin", "Руководитель"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Код",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True,
                db_table="role_permissions",
                related_name="gioia_roles",
                to="auth.permission",
                verbose_name="Разрешения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[0-9]{7,15}$", "Введите телефон: 7–15 цифр, возможен +."
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="accounts.UserRole",
                to="accounts.role",
                verbose_name="Роли",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Изменён"),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="accounts.role", verbose_name="Роль"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
