# Generated by Django 5.2.17 on 2026-09-12 08:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeraddress_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('name', models.CharField(max_length=200, verbose_name='Имя адресата')),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{7,15}$', 'Введите телефон: 7–15 цифр, возможен +.')], verbose_name='Телефон')),
                ('relationship', models.CharField(blank=True, max_length=200, verbose_name='Кем вам приходится')),
                ('notes', models.TextField(blank=True, verbose_name='Заметка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адресат',
                'verbose_name_plural': 'Адресаты',
                'db_table': 'customer_recipients',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='RecipientCelebrationDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('event_date', models.DateField(verbose_name='Дата поздравления')),
                ('repeats_annually', models.BooleanField(default=True, verbose_name='Повторяется каждый год')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='celebration_dates', to='accounts.customerrecipient', verbose_name='Адресат')),
            ],
            options={
                'verbose_name': 'Дата поздравления',
                'verbose_name_plural': 'Даты поздравлений',
                'db_table': 'recipient_celebration_dates',
                'ordering': ['event_date', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='customerrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='customer_recipient_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='recipientcelebrationdate',
            constraint=models.CheckConstraint(condition=models.Q(('title', ''), _negated=True), name='recipient_celebration_title_not_empty'),
        ),
    ]
