# Generated by Django 5.2.17 on 2026-09-11 18:44

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models

import apps.bouquet_builder.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomBouquet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("name", models.CharField(default="Мой букет", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("saved", "Сохранён"),
                            ("archived", "Архив"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "composition_seed",
                    models.PositiveBigIntegerField(
                        default=apps.bouquet_builder.models.generate_seed
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "packaging_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "addons_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("preview_svg", models.TextField(blank=True)),
                ("preview_data", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_bouquets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "custom_bouquets",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomBouquetFlower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "custom_bouquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flowers",
                        to="bouquet_builder.custombouquet",
                    ),
                ),
                (
                    "flower_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bouquet_items",
                        to="catalog.flowervariant",
                    ),
                ),
            ],
            options={
                "db_table": "custom_bouquet_flowers",
            },
        ),
        migrations.CreateModel(
            name="CustomBouquetGreenery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "custom_bouquet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="greenery",
                        to="bouquet_builder.custombouquet",
                    ),
                ),
                (
                    "greenery_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bouquet_items",
                        to="catalog.greenerytype",
                    ),
                ),
            ],
            options={
                "db_table": "custom_bouquet_greenery",
            },
        ),
        migrations.AddConstraint(
            model_name="custombouquet",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "saved", "archived"])),
                name="bouquet_valid_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("addons_price__gte", 0),
                    ("packaging_price__gte", 0),
                    ("subtotal__gte", 0),
                    ("total_price__gte", 0),
                ),
                name="bouquet_prices_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total_price",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("subtotal"), "+", models.F("packaging_price")
                            ),
                            "+",
                            models.F("addons_price"),
                        ),
                    )
                ),
                name="bouquet_total_matches",
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquetflower",
            constraint=models.UniqueConstraint(
                fields=("custom_bouquet", "flower_variant"), name="bouquet_flower_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquetflower",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="bouquet_flower_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquetflower",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="bouquet_flower_price_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquetgreenery",
            constraint=models.UniqueConstraint(
                fields=("custom_bouquet", "greenery_type"), name="bouquet_greenery_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquetgreenery",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="bouquet_greenery_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="custombouquetgreenery",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="bouquet_greenery_price_nonnegative",
            ),
        ),
    ]
