# Generated by Django 5.2.17 on 2026-09-12 08:36

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.bouquet_builder.models


class Migration(migrations.Migration):

    dependencies = [
        ('bouquet_builder', '0001_initial'),
        ('catalog', '0002_alter_flowercolor_options_alter_flowertype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custombouquet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Пользовательский букет', 'verbose_name_plural': 'Пользовательские букеты'},
        ),
        migrations.AlterModelOptions(
            name='custombouquetflower',
            options={'verbose_name': 'Цветок в букете', 'verbose_name_plural': 'Цветы в букете'},
        ),
        migrations.AlterModelOptions(
            name='custombouquetgreenery',
            options={'verbose_name': 'Зелень в букете', 'verbose_name_plural': 'Зелень в букете'},
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='addons_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='composition_seed',
            field=models.PositiveBigIntegerField(default=apps.bouquet_builder.models.generate_seed, verbose_name='Seed композиции'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='name',
            field=models.CharField(default='Мой букет', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='packaging_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='preview_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Данные предпросмотра'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='preview_svg',
            field=models.TextField(blank=True, verbose_name='Предпросмотр SVG'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('saved', 'Сохранён'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_bouquets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='custombouquet',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='custom_bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='bouquet_builder.custombouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='flower_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_items', to='catalog.flowervariant', verbose_name='Вариант цветка'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='custombouquetflower',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='custombouquetgreenery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='custombouquetgreenery',
            name='custom_bouquet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='greenery', to='bouquet_builder.custombouquet', verbose_name='Букет'),
        ),
        migrations.AlterField(
            model_name='custombouquetgreenery',
            name='greenery_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bouquet_items', to='catalog.greenerytype', verbose_name='Вид зелени'),
        ),
        migrations.AlterField(
            model_name='custombouquetgreenery',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='custombouquetgreenery',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
    ]
