# Generated by Django 5.2.17 on 2026-09-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bouquet_builder", "0002_alter_custombouquet_options_and_more"),
        ("catalog", "0002_alter_flowercolor_options_alter_flowertype_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custombouquet",
            name="packaging",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custom_bouquets",
                to="catalog.packagingtype",
                verbose_name="Упаковка",
            ),
        ),
    ]
