# Generated by Django 5.2.17 on 2026-09-11 18:44

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlowerColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "hex_color",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Используйте HEX-цвет #RRGGBB."
                            )
                        ],
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "flower_colors",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FlowerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("default_layer", models.IntegerField(default=10)),
                (
                    "default_scale",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("1.000"),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                    ),
                ),
            ],
            options={
                "db_table": "flower_types",
                "ordering": ["name", "pk"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("default_scale__gt", 0)),
                        name="flower_type_scale_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FlowerVariety",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "flower_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="varieties",
                        to="catalog.flowertype",
                    ),
                ),
            ],
            options={
                "db_table": "flower_varieties",
                "ordering": ["name", "pk"],
            },
        ),
        migrations.CreateModel(
            name="FlowerVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sku", models.CharField(max_length=64, unique=True)),
                (
                    "stem_length_cm",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "flower_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.flowercolor",
                    ),
                ),
                (
                    "flower_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.flowertype",
                    ),
                ),
                (
                    "flower_variety",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="catalog.flowervariety",
                    ),
                ),
            ],
            options={
                "db_table": "flower_variants",
                "ordering": ["sku"],
            },
        ),
        migrations.CreateModel(
            name="GreeneryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "retail_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
            ],
            options={
                "db_table": "greenery_types",
                "ordering": ["name", "pk"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retail_price__gte", 0)),
                        name="greenery_price_nonnegative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PackagingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
            ],
            options={
                "db_table": "packaging_types",
                "ordering": ["name", "pk"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)), name="packaging_price_nonnegative"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="flowervariety",
            constraint=models.UniqueConstraint(
                fields=("flower_type", "name"), name="flower_variety_type_name_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="flowervariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("purchase_price__gte", 0)),
                name="flower_purchase_price_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="flowervariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("retail_price__gte", 0)), name="flower_retail_price_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="flowervariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stem_length_cm__isnull", True), ("stem_length_cm__gt", 0), _connector="OR"
                ),
                name="flower_stem_length_positive",
            ),
        ),
    ]
