# Generated by Django 5.2.17 on 2026-09-12 08:36

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flowercolor',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='flowertype',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'Вид цветка', 'verbose_name_plural': 'Виды цветов'},
        ),
        migrations.AlterModelOptions(
            name='flowervariant',
            options={'ordering': ['sku'], 'verbose_name': 'Вариант цветка', 'verbose_name_plural': 'Варианты цветов'},
        ),
        migrations.AlterModelOptions(
            name='flowervariety',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'Сорт цветка', 'verbose_name_plural': 'Сорта цветов'},
        ),
        migrations.AlterModelOptions(
            name='greenerytype',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'Вид зелени', 'verbose_name_plural': 'Зелень'},
        ),
        migrations.AlterModelOptions(
            name='packagingtype',
            options={'ordering': ['name', 'pk'], 'verbose_name': 'Вид упаковки', 'verbose_name_plural': 'Виды упаковки'},
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='hex_color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Используйте HEX-цвет #RRGGBB.')], verbose_name='Цвет HEX'),
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flowercolor',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='default_layer',
            field=models.IntegerField(default=10, verbose_name='Слой по умолчанию'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='default_scale',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Масштаб по умолчанию'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='flowertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='flower_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.flowercolor', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='flower_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.flowertype', verbose_name='Вид цветка'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='flower_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='catalog.flowervariety', verbose_name='Сорт'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='sku',
            field=models.CharField(max_length=64, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='stem_length_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина стебля, см'),
        ),
        migrations.AlterField(
            model_name='flowervariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='flowervariety',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='flowervariety',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flowervariety',
            name='flower_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='varieties', to='catalog.flowertype', verbose_name='Вид цветка'),
        ),
        migrations.AlterField(
            model_name='flowervariety',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='flowervariety',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='flowervariety',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='greenerytype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Адрес (slug)'),
        ),
        migrations.AlterField(
            model_name='packagingtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Изменён'),
        ),
    ]
